
NAME	=	libft.a

C_DIR	=	src

O_DIR	=	obj

SRCS	=	${patsubst %, ${C_DIR}/%, ${C_FILES}}

C_FILES	=	get_next_line.c\
			ft_strrchr.c\
			ft_putendl_fd.c\
			ft_memmove.c\
			ft_lstdelone.c\
			ft_isprint.c\
			ft_strlcpy.c\
			ft_strtrim.c\
			ft_putnbr_fd.c\
			ft_memset.c\
			ft_lstiter.c\
			ft_atoi.c\
			ft_strclen.c\
			ft_substr.c\
			ft_putstr_fd.c\
			ft_memcmp.c\
			ft_lstlast.c\
			ft_bzero.c\
			ft_memchr.c\
			ft_strlen.c\
			ft_split.c\
			ft_lstnew.c\
			ft_lstmap.c\
			ft_calloc.c\
			ft_tolower.c\
			ft_strmapi.c\
			ft_strchr.c\
			ft_lstsize.c\
			ft_itoa.c\
			ft_isalnum.c\
			ft_toupper.c\
			ft_strjoin.c\
			ft_strcmp.c\
			ft_memccpy.c\
			ft_lstadd_back.c\
			ft_isalpha.c\
			ft_strncmp.c\
			ft_strlcat.c\
			ft_strdup.c\
			ft_lstadd_front.c\
			ft_isascii.c\
			ft_strnstr.c\
			ft_putchar_fd.c\
			ft_memcpy.c\
			ft_lstclear.c\
			ft_isdigit.c

OBJS	=	${patsubst ${C_DIR}/%, ${O_DIR}/%, ${SRCS:.c=.o}}

CC		=	clang

CFLAGS	=	-I. -Wall -Wextra -Werror #fsanitize=address

all:		${NAME}

$(NAME):	${OBJS}
			ar rc ${NAME} ${OBJS}


${O_DIR}/%.o : ${C_DIR}/%.c
			@mkdir -p obj
			${CC} ${CFLAGS} -c $< -o $@

.PHONY:		clean fclean re bonus .c.o all

clean:
			rm -rf ${O_DIR}

fclean:		clean
			rm -f ${NAME}

re:			fclean all
